### ISSUE TITLE
Failed to load SidecarCore

### ISSUE THREAD

**Issue by sadboymarvin** [pookjw/SidecarPatcher#104]
Hi,

I got a macbook air 2013. Got the following error:

mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
**Fatal error: Failed to load SidecarCore.: file main/main.swift, line 225**

Any ideas how to fix this?

Thanks a lot

**Comment by deeheem** [comment]
I'm getting the same error. Full stack trace:
```swift
SidecarPatcher (Version 14)
GitHub : https://github.com/pookjw/SidecarPatcher
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
Fatal error: Failed to load SidecarCore.: file main/main.swift, line 225
Stack dump:
0.	Program arguments: /Library/Developer/CommandLineTools/usr/bin/swift -frontend -interpret /Users/deeheem/Downloads/SidecarPatcher-master/main.swift -enable-objc-interop -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -color-diagnostics -target-sdk-version 11.0 -module-name main 
1.	Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
2.	While running user code "/Users/deeheem/Downloads/SidecarPatcher-master/main.swift"
0  swift                    0x0000000109f6dc15 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift                    0x0000000109f6e332 SignalHandler(int) + 610
2  libsystem_platform.dylib 0x00007fff2038bd7d _sigtramp + 29
3  libsystem_c.dylib        0x00007fff88ac05a0 __global_locale + 0
4  libsystem_c.dylib        0x000000010ebd4a7c __global_locale + 18446603342765442268
5  libsystem_c.dylib        0x000000010ebcf9e5 __global_locale + 18446603342765421637
6  swift                    0x00000001057cc605 llvm::orc::runAsMain(int (*)(int, char**), llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::Optional<llvm::StringRef>) + 1221
7  swift                    0x00000001057a9ebb swift::RunImmediately(swift::CompilerInstance&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, swift::IRGenOptions const&, swift::SILOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >&&) + 6763
8  swift                    0x00000001057855ce performCompileStepsPostSILGen(swift::CompilerInstance&, swift::CompilerInvocation const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 2446
9  swift                    0x00000001057757ba swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 21802
10 swift                    0x00000001056f62c1 main + 1265
11 libdyld.dylib            0x00007fff20362631 start + 1
12 libdyld.dylib            0x000000000000000c start + 18446603339975743964
[1]    1309 illegal hardware instruction  sudo swift /Users/deeheem/Downloads/SidecarPatcher-master/main.swift
```

Please help.

**Comment by albertoacj** [comment]
Same error here,  I can't find SideCore in system, tried to set chmod 777 in folder even with SIP disable return chmod not permitted.

**Comment by vtungn** [comment]
It doesn't work with macOS 11.0 Big Sur.

**Comment by robbelroot** [comment]
@vtungn Yeah, can't get it to work as well, sad :(. I don't want to purchase a new 2k€ Macbook just for using this function..

**Comment by jofftiquez** [comment]
Having same issue, Big Sur on Macbook Pro 2015

**Comment by guilpejon** [comment]
Wish I found this thread sooner. Same problema here with macbook pro 2015 big sur.

**Comment by r-wilder** [comment]
Same issue for another macbook pro early 15 on Bir Sur. 

`mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
main/main.swift:225: Fatal error: Failed to load SidecarCore.`

**Comment by RiekeZoe** [comment]
I've got a similar problem (Mac early 2015, Big Sur).
